format_version: 10
pipelines:
  expense-destroy:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-916dd6a:
        git: https://github.com/naveendevops453/expense-terraform
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:5Lr6oPcneduyEBV9/q+3qg==:D7QBStsbr/NJykNvBkxGLQ=="
      vault_token: "AES:ZuhqLvrGETJz4E1yFc4U1A==:Z+o2KCQN2RQXlqavXOlXxpA6k9Oufn7Akw/3lFQQHVo="
    stages:
      - DEV:
          fetch_materials: true
          environment_variables: { env: dev, action: destroy }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
                - exec: { command: bash ,  arguments: [ "run.sh" ] }

      - PROD:
          fetch_materials: true
          environment_variables: { env: prod, action: destroy }
          jobs:
            terraform:
              tasks:
                - exec: { command: bash ,  arguments: [ "run.sh" ] }