format_version: 10
pipelines:
  tools-create:
    group: Terraform
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-916dd6a:
        git: https://github.com/naveendevops453/tools-automation.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - create:
          fetch_materials: true
          environment_variables: { env: dev }
          approval: {type: manual}
          jobs:
            terraform:
              tasks:
                - exec: { command: terraform ,  arguments: [ "init" ] }
                - exec: { command: terraform,  arguments: [ "apply", "-auto-approve" ] }