format_version: 10
pipelines:
  backend:
    group: App-Deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-916dd6a:
        git: https://github.com/naveendevops453/expense-anisble
        shallow_clone: true
        auto_update: true
        branch: main
    secure_variables:
      SSH_PASSWORD: "AES:5Lr6oPcneduyEBV9/q+3qg==:D7QBStsbr/NJykNvBkxGLQ=="
    environment_variables:
      component: backend
    template: ansible-app-deployment